apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sleep-getblocks
  name: sleep-getblocks
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sleep-getblocks
status:
  loadBalancer: {}
